def format_result(result):  
    """Convert a result dict to a readable string."""  
    if not result:  
        return "No effect"  
    parts = []  
    for stat, value in result.items():  
        sign = "+" if value >= 0 else ""  
        unit = "$" if stat == "savings" else ""  
        parts.append(f"{sign}{unit}{value:,} {stat}")  
    return ", ".join(parts)  
  
  
def apply_result(scott, result):  
    """Apply a result dict to scott's scores and stats."""  
    for stat, value in result.items():  
        if stat in scott.scores:  
            scott.scores[stat] += value  
        elif stat in scott.stats:  
            scott.scores[stat] = min(6, scott.stats[stat] + value) 
        elif stat == "savings":  
            scott.savings += value  

def married(scott):  
    scott.is_married = True   # or whatever side effect you need  
    print("  You are now married!")  
  
life_events = [
    {
        "description":      'Go back to school',
        "optional":         True,
        "requires":         8,
        "type":             'career',
        "buff_stat":        'intelligence',
        "succeed_msg":      'You go back to U of A for a masters in nanotechnology!',
        "fail_msg":         'You applied to a few labs and got rejected',
        "succeed_function": 'Set income to 2000',
        "results": {
            "pass":    {},
            "succeed": {"savings": -50000, "career": 10, "happiness": -2, "time": -1, "intelligence": 1},
            "fail":    {"career": -5, "happiness": -5, "savings": -500, "intelligence": -1},
        },
    },
    {
        "description":      'Join a band',
        "optional":         True,
        "requires":         4,
        "type":             'pursuits',
        "buff_stat":        'charisma',
        "succeed_msg":      'Meet the newest bassit of Medical Pilots lol',
        "fail_msg":         "Your audition didn't go according to plan",
        "results": {
            "pass":    {},
            "succeed": {"relationships": 8, "happiness": 2, "charisma": 1, "time": -1},
            "fail":    {"happiness": -5},
        },
    },
    {
        "description":      'Write and sell a program',
        "optional":         True,
        "requires":         12,
        "type":             'career',
        "buff_stat":        'intelligence',
        "succeed_msg":      'Someone actually wants your ingenius recipe website',
        "fail_msg":         'Your only bid was from Scaa wirewess surutions for $5',
        "succeed_function": 'Sell price will be randomly generated based on how much over roll you get.',
        "results": {
            "pass":    {},
            "succeed": {"career": 15, "happiness": 5, "intelligence": 1},
            "fail":    {"career": -10, "savings": -500, "luck": -1},
        },
    },
    {
        "description":      'Sell your video game',
        "optional":         True,
        "requires":         12,
        "type":             'pursuits',
        "buff_stat":        'intelligence',
        "succeed_msg":      'Monster trucks make money',
        "fail_msg":         'You post it for free on Steam and have 5 mixed reviews. All exposure is good exposure...right?',
        "succeed_function": 'Sell price will be randomly generated based on how much over roll you get',
        "results": {
            "pass":    {},
            "succeed": {"happiness": 10, "luck": 1},
            "fail":    {"happiness": -5, "luck": -1},
        },
    },
    {
        "description":      'Relocate for your job',
        "optional":         True,
        "requires":         7,
        "type":             'career',
        "buff_stat":        'time',
        "succeed_msg":      'Benu moves to Seatle and you embrace the rain',
        "fail_msg":         'You relocate to Seatle but Benu goes under less than a year later',
        "results": {
            "pass":    {},
            "succeed": {"career": 20, "happiness": -5, "income": 2000},
            "fail":    {"career": -10, "happiness": -10, "savings": -1000, "time": -1},
        },
    },
    {
        "description":      'Move cities',
        "optional":         True,
        "requires":         7,
        "type":             None,
        "buff_stat":        None,
        "succeed_msg":      'Spend a few years in Calgary',
        "fail_msg":         "You decide Carbon is the Vancouver of Alberta. Spolier Alert: It isn't.",
        "results": {
            "pass":    {},
            "succeed": {"relationships": 5, "happiness": -5, "luck": 1, "charisma": 1},
            "fail":    {"relationships": -5, "happiness": -10},
        },
    },
    {
        "description":      'Host a party',
        "optional":         True,
        "requires":         3,
        "type":             'pursuits',
        "buff_stat":        'charisma',
        "succeed_msg":      'Everyone has a blast and no one pukes in your bathroom',
        "fail_msg":         'You sent the wrong date on the invites.',
        "results": {
            "pass":    {},
            "succeed": {"relationships": 5, "happiness": 5, "charisma": 1},
            "fail":    {"relationships": -2, "happiness": -2},
        },
    },
    {
        "description":      'Go to karaoke',
        "optional":         True,
        "requires":         2,
        "type":             'pursuits',
        "buff_stat":        'charisma',
        "succeed_msg":      'You crushed that solo!',
        "fail_msg":         "You preformed a solo! Luckily you drank enough you don't remeber.. unforutneatly Andrew recorded the entire thing",
        "results": {
            "pass":    {},
            "succeed": {"relationships": 5},
            "fail":    {"happiness": -2},
        },
    },
    {
        "description":      'Get into gardening',
        "optional":         True,
        "requires":         2,
        "type":             'pursuits',
        "buff_stat":        None,
        "succeed_msg":      'You get really into grafting apple varieties',
        "fail_msg":         'You get an ant infestation that kills everything',
        "results": {
            "pass":    {},
            "succeed": {"happiness": 5, "health": 5, "time": -1, "intelligence": 1},
            "fail":    {"happiness": -2},
        },
    },
    {
        "description":      'Visit your relatives',
        "optional":         True,
        "requires":         5,
        "type":             'relationships',
        "buff_stat":        None,
        "succeed_msg":      'Take a trip to Lethbridge',
        "fail_msg":         'It was a little akward',
        "results": {
            "pass":    {},
            "succeed": {"relationships": 15, "happiness": 10, "charisma": 1},
            "fail":    {"relationships": -5},
        },
    },
    {
        "description":      'Attend a family reunion',
        "optional":         True,
        "requires":         5,
        "type":             'relationships',
        "buff_stat":        None,
        "succeed_msg":      'Take a trip to Fernie',
        "fail_msg":         'You took 5 vacation days to sit in a circle and bicker',
        "results": {
            "pass":    {},
            "succeed": {"relationships": 15, "happiness": 10, "charisma": 1, "time": -1},
            "fail":    {"relationships": -10},
        },
    },
    {
        "description":      'Adopt a cat',
        "optional":         True,
        "requires":         10,
        "type":             None,
        "buff_stat":        None,
        "succeed_msg":      'You and Chester are insperable! Jessica sews him a bowtie',
        "fail_msg":         'Chester escapes and get hit by a car two weeks later.',
        "results": {
            "pass":    {},
            "succeed": {"happiness": 3, "income": -200, "luck": 1},
            "fail":    {"happiness": -5, "savings": -50},
        },
    },
    {
        "description":      'Get married',
        "optional":         True,
        "requires":         13,
        "type":             'relationships',
        "buff_stat":        'charisma',
        "succeed_msg":      'Your vows were poetic genius and left everyone in tears',
        "fail_msg":         'It rained, everyone got food poisoning, you had wedding crashers and someone proposed during speeches.',
        "results": {
            "pass":    {},
            "succeed": {"relationships": 25, "happiness": 10, "savings": -30000, "charisma": 2, "time": -2},
            "fail":    {"relationships": -10, "happiness": -10, "savings": -10000, "luck": -1, "time": -2},
        },
    },
    {
        "description":      'Run a half marathon',
        "optional":         True,
        "requires":         10,
        "type":             'pursuits',
        "buff_stat":        'fitness',
        "succeed_msg":      'Woah! Sub 2 hours!',
        "fail_msg":         "You got heat stroke and didn't finish",
        "results": {
            "pass":    {},
            "succeed": {"health": 10, "savings": -100, "fitness": 2, "time": -1},
            "fail":    {"health": -5, "fitness": -1},
        },
    },
    {
        "description":      'Buy an apartment',
        "optional":         True,
        "requires":         9,
        "type":             None,
        "buff_stat":        None,
        "succeed_msg":      'Get a two bedroom overlooking a park',
        "fail_msg":         'You skipped out on an inspection and discover mold behind the fridge',
        "results": {
            "pass":    {},
            "succeed": {"happiness": 15, "savings": -50000, "income": -4000, "time": -1, "intelligence": 1},
            "fail":    {"happiness": -10, "savings": -20000, "luck": -1},
        },
    },
    {
        "description":      'Buy a new car',
        "optional":         True,
        "requires":         7,
        "type":             None,
        "buff_stat":        None,
        "succeed_msg":      'It was time. The regal has lived a good life',
        "fail_msg":         'It stalls on the Henday the minute you drive it off the lot.',
        "results": {
            "pass":    {},
            "succeed": {"happiness": 8, "savings": -10000, "time": 1},
            "fail":    {"happiness": -5, "savings": -7000, "luck": -1},
        },
    },
    {
        "description":      'Go on a holiday',
        "optional":         True,
        "requires":         6,
        "type":             'pursuits',
        "buff_stat":        'time',
        "succeed_msg":      'About damn time!',
        "fail_msg":         'Goal: Costa Rica. Reality: A hurricane grounds your flight in Nebraska.',
        "results": {
            "pass":    {},
            "succeed": {"relationships": 10, "happiness": 10, "savings": -8000, "luck": 1, "fitness": 1, "time": -1},
            "fail":    {"relationships": -5, "happiness": -5, "savings": -5000},
        },
    },
    {
        "description":      'Adopt a dog',
        "optional":         True,
        "requires":         8,
        "type":             None,
        "buff_stat":        'fitness',
        "succeed_msg":      'Jessica and Cooper "coexist" - It\'s the best you could ask for',
        "fail_msg":         'You get a reactionary chihuahua. Jessica glares at it often',
        "results": {
            "pass":    {},
            "succeed": {"relationships": 5, "happiness": 8, "income": -1000, "fitness": 1, "time": -1},
            "fail":    {"relationships": -2, "happiness": -5, "savings": -300, "intelligence": -2},
        },
    },
    {
        "description":      'Become a landlord',
        "optional":         True,
        "requires":         11,
        "type":             'career',
        "buff_stat":        'time',
        "succeed_msg":      'Your tennants are very respectful and reliable suprisingly',
        "fail_msg":         'You evict your tennants after they fail to pay rent for 3 months. Turns out they had a grow-opt in the basement',
        "results": {
            "pass":    {},
            "succeed": {"career": 15, "savings": -30000, "income": 5000, "luck": -1, "time": -1, "intelligence": 2},
            "fail":    {"career": -10, "happiness": -8, "savings": -15000, "time": -1},
        },
    },
    {
        "description":      'See Vulfpeck in concert',
        "optional":         True,
        "requires":         7,
        "type":             'pursuits',
        "buff_stat":        None,
        "succeed_msg":      'It was everything you imagined. Cory Wong dedicates a song to you.',
        "fail_msg":         'They cancel suddenly the day before due to band "creative differences"',
        "results": {
            "pass":    {},
            "succeed": {"happiness": 8, "savings": -500, "luck": 1},
            "fail":    {"happiness": -8},
        },
    },
    {
        "description":      'Get into metallurgy',
        "optional":         True,
        "requires":         7,
        "type":             'pursuits',
        "buff_stat":        None,
        "succeed_msg":      'You are one project away from buying a furnace',
        "fail_msg":         "You nearly lose a finger and decide it's not for you",
        "results": {
            "pass":    {},
            "succeed": {"happiness": 5, "time": -1, "intelligence": 1},
            "fail":    {"happiness": -1},
        },
    },
    {
        "description":      'Go on a bike trip',
        "optional":         True,
        "requires":         6,
        "type":             None,
        "buff_stat":        'fitness',
        "succeed_msg":      'You bike down to Drumheller to see the dino museum',
        "fail_msg":         'Get a flat tire in the middle of rural Alberta and have to hitch hike to Hana for a rescue',
        "results": {
            "pass":    {},
            "succeed": {"happiness": 5, "health": 10, "fitness": 2},
            "fail":    {"health": -8},
        },
    },
    {
        "description":      'Do a triathalon',
        "optional":         True,
        "requires":         8,
        "type":             None,
        "buff_stat":        'fitness',
        "succeed_msg":      'Really? You enjoyed that?',
        "fail_msg":         'You rage quit when a fish touches your foot during the swim portion',
        "results": {
            "pass":    {},
            "succeed": {"happiness": 5, "health": 20, "savings": -100, "fitness": 2, "time": -2},
            "fail":    {"happiness": -2, "health": -15, "fitness": -2},
        },
    },
    {
        "description":      'Shave your head',
        "optional":         True,
        "requires":         2,
        "type":             None,
        "buff_stat":        None,
        "succeed_msg":      'Because why not',
        "fail_msg":         'Benjie calls you a skinhead',
        "results": {
            "pass":    {},
            "succeed": {"happiness": 1},
            "fail":    {"savings": -1},
        },
    },
    {
        "description":      'Start a side buisness',
        "optional":         True,
        "requires":         16,
        "type":             'career',
        "buff_stat":        'intelligence',
        "succeed_msg":      'You start a basket weaving buisness... yes, really. And its successful... yes, really',
        "fail_msg":         'You spend 5 months deciding on a name and logo... you forgot to think of a concept though',
        "results": {
            "pass":    {},
            "succeed": {"career": 25, "happiness": 10, "savings": -20000, "income": 3000, "luck": 2, "time": -1, "intelligence": 1},
            "fail":    {"career": -15, "happiness": -8, "savings": -10000, "intelligence": -2},
        },
    },
    {
        "description":      'Build a house',
        "optional":         True,
        "requires":         18,
        "type":             None,
        "buff_stat":        'time',
        "succeed_msg":      'Some people dream about their future family or job. But you have been dreaming about crown mouldings.',
        "fail_msg":         'You buy a fixer-upper. Turns out is needs ALOT of fixing and you move back home while you redo the drywall',
        "results": {
            "pass":    {},
            "succeed": {"happiness": 20, "savings": -70000, "income": -2000, "fitness": 2, "time": -2, "intelligence": 2},
            "fail":    {"happiness": -15, "savings": -50000, "income": -500, "luck": -1, "time": -2},
        },
    },
    {
        "description":      'Read a book',
        "optional":         True,
        "requires":         3,
        "type":             'pursuits',
        "buff_stat":        None,
        "succeed_msg":      'Who knew you loved romanticy',
        "fail_msg":         'You lose a bet with Jarod and have to read ACOTAR. Its exactly as bad as you thought it would be.',
        "results": {
            "pass":    {},
            "succeed": {"happiness": 5, "health": 5, "intelligence": 1},
            "fail":    {"happiness": -1},
        },
    },
    {
        "description":      'Get voluntary baloon dialation',
        "optional":         True,
        "requires":         6,
        "type":             None,
        "buff_stat":        'fitness',
        "succeed_msg":      'You can swallow again!',
        "fail_msg":         'You get throat spasms every day. But at least you can swallow.',
        "results": {
            "pass":    {},
            "succeed": {"health": 10},
            "fail":    {"health": -10},
        },
    },
    {
        "description":      'Go skydiving',
        "optional":         True,
        "requires":         5,
        "type":             'pursuits',
        "buff_stat":        None,
        "succeed_msg":      'It was exhilirating! You told you mom in excruitiing detail. She almost fainted.',
        "fail_msg":         'You chicken out at the last minute and take the flight down',
        "results": {
            "pass":    {},
            "succeed": {"happiness": 5},
            "fail":    {"happiness": -1},
        },
    },
    {
        "description":      'Attend a friends wedding',
        "optional":         True,
        "requires":         8,
        "type":             'relationships',
        "buff_stat":        'charisma',
        "succeed_msg":      'Close out the night on the dance floor',
        "fail_msg":         'You were responsible for the rings but lost them going through airport security',
        "results": {
            "pass":    {},
            "succeed": {"relationships": 10, "happiness": 5, "savings": -100, "charisma": 1},
            "fail":    {"relationships": -8},
        },
    },
    {
        "description":      'Learn a new language',
        "optional":         True,
        "requires":         10,
        "type":             'pursuits',
        "buff_stat":        'intelligence',
        "succeed_msg":      'De alguna manera te vuelves fluido',
        "fail_msg":         'You accidentally insult your spanish neibough',
        "results": {
            "pass":    {},
            "succeed": {"career": 10, "happiness": 10, "time": -2, "intelligence": 3},
            "fail":    {"career": -5, "time": -1},
        },
    },
]